spring:
  application:
    name: flowtxt-api
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  config:
    import: optional:file:.env

  data:
    mongodb:
      # Conex√£o com MongoDB do docker-compose
      uri: mongodb://root:rootpassword@localhost:27017/flowtxt?authSource=admin
  redis:
    host: localhost
    port: 6379

  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8080

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

logging:
  level:
    root: INFO
    ca.flowtxt: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG
    org.mongodb.driver.protocol.command: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html